import type { Metadata } from "next";
import localFont from "next/font/local";
import { WebContainerProvider } from "./contexts/web-container-context";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import "@radix-ui/themes/styles.css";
import {Theme} from "@radix-ui/themes";
import { Inter } from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col`}
      >
    <WebContainerProvider>
        <Theme>
            <Navbar />
            {children}
            <Footer />
        </Theme>
    </WebContainerProvider>
      </body>
    </html>
  );
}
